language: node_js
node_js:
  - node

cache:
  directories:
    - "frontend/node_modules"
    - "backend/node_modules"

jobs:
  include:
    - stage: test
      before_script:
        - cd frontend && npm i
        - npm i codecov
      script:
        - npm test -- --coverage
        - ./node_modules/.bin/codecov

    - stage: test
      before_script:
        - cd backend && npm i
        - npm i codecov

    - stage: build
      script: cd frontend && npm run build