version: "3"
services:
  web:
    image: ebm1718travis/clock-livecoding:latest
    # depends_on:
    #   - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb/clock-livecoding
    networks:
      local:
      ebm-filrouge:
        aliases:
          - clock-livecoding
  # mongodb:
  #   image: mongo
  #   networks:
  #     - local
networks:
  local:
  ebm-filrouge:
    external: true 
