version: "3"
services:
  web:
    image: ebm1718travis/ebm-boilerplate:latest
    depends_on:
      # - mongodb
    environment:
      - APP_PORT=4000
      - MONGODB_URI=mongodb://mongodb/node-auth
    networks:
      local:
      ebm-filrouge:
        aliases:
          - ebm-boilerplate
  # mongodb:
  #   image: mongo
  #   networks:
  #     - local
networks:
  local:
  ebm-filrouge:
    external: true 
